// BridgeLinkTestPlugin.idl : IDL source for BridgeLinkTestPlugin.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (BridgeLinkTestPlugin.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";


[
	uuid(B2DE7B2E-5D72-4E95-9F99-302E9B7E3C08),
	version(1.0),
	helpstring("BridgeLinkTestPlugin 1.0 Type Library")
]
library BRIDGELINKTESTPLUGINLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	[
		uuid(EA779BA8-2CD8-4BE6-8C67-BFD91D7D2F52),
		helpstring("Plugin Class")
	]
	coclass Plugin
	{
		[default] interface IUnknown;
	};

   [
      uuid(758C6FD8-8AC1-44ba-BD80-5E72205244A5)
   ]
   coclass BridgeLinkExampleComponentInfo
   {
      interface IUnknown;
   }
};
